// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwQ39_j6BURh7khqEYAluqJNNDc-nt_Zc',
    appId: '1:72772391929:web:50105c453e1cc4bd9c6328',
    messagingSenderId: '72772391929',
    projectId: 'ctiktok-d09a9',
    authDomain: 'ctiktok-d09a9.firebaseapp.com',
    storageBucket: 'ctiktok-d09a9.appspot.com',
    measurementId: 'G-EJEQ1YPDSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZwdFZfGh1UsxH-hLg6wD8CQg7HWHblvw',
    appId: '1:72772391929:android:202dbb44a73d3bb69c6328',
    messagingSenderId: '72772391929',
    projectId: 'ctiktok-d09a9',
    storageBucket: 'ctiktok-d09a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZIfowl0a4WeIHOb7taBQKAFqX8z9fWI',
    appId: '1:72772391929:ios:1ff1fd16d24f48eb9c6328',
    messagingSenderId: '72772391929',
    projectId: 'ctiktok-d09a9',
    storageBucket: 'ctiktok-d09a9.appspot.com',
    iosClientId: '72772391929-nuda66fm9u5l33qav24oueghpp9anpit.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHZIfowl0a4WeIHOb7taBQKAFqX8z9fWI',
    appId: '1:72772391929:ios:1ff1fd16d24f48eb9c6328',
    messagingSenderId: '72772391929',
    projectId: 'ctiktok-d09a9',
    storageBucket: 'ctiktok-d09a9.appspot.com',
    iosClientId: '72772391929-nuda66fm9u5l33qav24oueghpp9anpit.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctiktok',
  );
}
